import { ImageResponse } from "next/og";

export const runtime = "edge";
export const alt = "Compass Opportunity Card";

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const title = searchParams.get("title") ?? "Product Opportunity";
  const score = searchParams.get("score") ?? "0";
  const signals = searchParams.get("signals") ?? "0";
  const problem = searchParams.get("problem") ?? "";

  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          width: "100%",
          height: "100%",
          background: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)",
          padding: 48,
          fontFamily: "system-ui, sans-serif",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flex: 1,
            border: "2px solid rgba(148, 163, 184, 0.2)",
            borderRadius: 16,
            padding: 32,
            background: "rgba(15, 23, 42, 0.6)",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 12,
              marginBottom: 24,
            }}
          >
            <div
              style={{
                width: 40,
                height: 40,
                borderRadius: 10,
                background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 20,
              }}
            >
              🧭
            </div>
            <span style={{ color: "#94a3b8", fontSize: 14 }}>Compass</span>
          </div>

          <h1
            style={{
              fontSize: 28,
              fontWeight: 700,
              color: "#f8fafc",
              margin: 0,
              marginBottom: 16,
              lineHeight: 1.3,
            }}
          >
            {title}
          </h1>

          {problem ? (
            <p
              style={{
                fontSize: 16,
                color: "#94a3b8",
                margin: 0,
                marginBottom: 24,
                lineHeight: 1.5,
                maxWidth: 480,
              }}
            >
              {problem.length > 120 ? `${problem.slice(0, 120)}...` : problem}
            </p>
          ) : null}

          <div
            style={{
              display: "flex",
              gap: 24,
              alignItems: "center",
              marginTop: "auto",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "12px 20px",
                background: "rgba(59, 130, 246, 0.2)",
                borderRadius: 12,
              }}
            >
              <span style={{ color: "#94a3b8", fontSize: 14 }}>Opportunity Score</span>
              <span style={{ color: "#60a5fa", fontSize: 24, fontWeight: 700 }}>{score}</span>
            </div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "12px 20px",
                background: "rgba(34, 197, 94, 0.2)",
                borderRadius: 12,
              }}
            >
              <span style={{ color: "#94a3b8", fontSize: 14 }}>Demand Signals</span>
              <span style={{ color: "#4ade80", fontSize: 24, fontWeight: 700 }}>{signals}</span>
            </div>
          </div>

          <div
            style={{
              marginTop: 24,
              paddingTop: 20,
              borderTop: "1px solid rgba(148, 163, 184, 0.2)",
              color: "#64748b",
              fontSize: 12,
            }}
          >
            Generated by Compass · AI Product Intelligence Platform
          </div>
        </div>
      </div>
    ),
    {
      width: 600,
      height: 400,
    }
  );
}
