"use client";

import { useRef, useState } from "react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, Share2, Copy, Check } from "lucide-react";
import { cn } from "@/lib/utils";

type ShareableInsightCardProps = {
  title: string;
  items: { name: string; count?: number }[];
  className?: string;
};

export function ShareableInsightCard({
  title,
  items,
  className,
}: ShareableInsightCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);

  const exportAsPng = async () => {
    if (!cardRef.current) return;
    try {
      const html2canvas = (await import("html2canvas")).default;
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: "#ffffff",
        scale: 2,
      });
      const link = document.createElement("a");
      link.download = `compass-insight-${Date.now()}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (err) {
      console.error("PNG export failed:", err);
    }
  };

  const copyForX = () => {
    const text = `Top User Requests\n\n${items.map((i, idx) => `${idx + 1}. ${i.name}${i.count ? ` (${i.count} mentions)` : ""}`).join("\n")}\n\nGenerated by Compass`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card className={cn("overflow-hidden", className)} ref={cardRef}>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <span className="text-sm font-semibold">{title}</span>
          <DropdownMenu>
            <DropdownMenuTrigger
              className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md hover:bg-accent hover:text-accent-foreground"
              aria-label="Share options"
            >
              <Share2 className="h-4 w-4" />
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={exportAsPng}>
                <Download className="mr-2 h-4 w-4" />
                Export as PNG
              </DropdownMenuItem>
              <DropdownMenuItem onClick={copyForX}>
                {copied ? (
                  <Check className="mr-2 h-4 w-4 text-emerald-500" />
                ) : (
                  <Copy className="mr-2 h-4 w-4" />
                )}
                Copy for X post
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </CardHeader>
      <CardContent>
        <ol className="space-y-1 text-sm">
          {items.map((item, i) => (
            <li key={i} className="flex gap-2">
              <span className="text-muted-foreground font-mono">{i + 1}.</span>
              <span>{item.name}</span>
              {item.count != null && (
                <span className="text-muted-foreground">({item.count} mentions)</span>
              )}
            </li>
          ))}
        </ol>
        <p className="mt-3 text-[10px] text-muted-foreground">Generated by Compass</p>
      </CardContent>
    </Card>
  );
}
